### ISSUE TITLE
Consommations

### ISSUE THREAD

**Issue by DomyDGJ** [TheGui01/Frisquet-connect-for-home-assistant#11]
Bonjour

Je viens d'installer votre programme dans Home Assistant, sans problème grâce à vos explications.
L'ensemble fonctionne parfaitement.
Je vous en remercie.
Sur l'application Frisquet Connect, il est possible de voir les consommations mensuelles pour le chauffage et pour l'eau chaude sanitaire.
Pensez vous possible de récupérer ces informations dans Home Assistant ?
Si oui, comment puis-je faire ?
Merci d'avance pour votre aide.

Dominique

**Comment by TheGui01** [comment]
Bonjour @DomyDGJ ,

Je ne suis pas capable en l'état de récupérer ces infos.
Je me renseigne auprès de la personne qui m'a partagé les requêtes API.
Je vous tiendrai au courant de son retour.

**Comment by Galen-Titanium** [comment]
Bonjour, 

J'avoue que je serais aussi interessé par la remontée des consommations eau chaude et chauffage. 

j'ai parcouru je pense les même doc et il semble que :

Récupération des statistiques de consommation (NON TESTE) :
curl --location 'https://fcutappli.frisquet.com/api/v1/sites/wwwwwwwwwwwwww/conso?token=xxxxxxxxxxxxxxxxxxxx&types%5B%5D=CHF&types%5B%5D=SAN'
avec "wwwwwwwwwwwww" = Id de la chaudière et "xxxxxxxxxxxxxxx" = Token

avec cela ça doit être possible j'ai tenté de faire avec ma chaudière le curl retourne un truc mais apres je ne suis pas suffisamment compètent pour faire le nécessaire et proposer l'amélioration

SI besoin je peux essayer d'aider à avec mes modeste connaissance

**Comment by TheGui01** [comment]
> [Doc_API.txt](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/files/14802595/Doc_API.txt)
> Bonjour, 
> 
> J'avoue que je serais aussi interessé par la remontée des consommations eau chaude et chauffage. 
> 
> j'ai parcouru je pense les même doc et il semble que :
> 
> Récupération des statistiques de consommation (NON TESTE) :
> curl --location 'https://fcutappli.frisquet.com/api/v1/sites/wwwwwwwwwwwwww/conso?token=xxxxxxxxxxxxxxxxxxxx&types%5B%5D=CHF&types%5B%5D=SAN'
> avec "wwwwwwwwwwwww" = Id de la chaudière et "xxxxxxxxxxxxxxx" = Token
> 
> avec cela ça doit être possible j'ai tenté de faire avec ma chaudière le curl retourne un truc mais apres je ne suis pas suffisamment compètent pour faire le nécessaire et proposer l'amélioration
> 
> SI besoin je peux essayer d'aider avec mes modestes connaissances
> 
> 

Bien vu ! J'ai oublié que c'etait dedans... le boulet...
Je regarde ca durant ce we pascal et je vous tiens au courant

**Comment by Galen-Titanium** [comment]
Ohhhhh génial :)

**Comment by TheGui01** [comment]
Bonjour @DomyDGJ @Galen-Titanium 
Je viens de créer une version beta 1.9.0.1
Si vous pouvez l'installer et me faire un retour...
J'ai créé 2 capteurs pour les conso de chauffage et d'eau chaude. Ces capteurs vont vous afficher la valeur en kWh pour le mois en cours. 
L'idée est de les ajouter a votre tableau de bord énergie dans les consos de gaz (https://homeassistant:8123/config/energy)

J'ai des doutes sur son fonctionnement mais si tout se passe bien, vous devriez avoir un gros pic de conso qui s'affichera au bout de qq heures car il va remonter toute la conso du mois sur la dernière tranches de 30 min. Ceci est supprimable dans
https://homeassistant:8123/developer-tools/statistics...
Ensuite le comportement devrait etre correct.

Mes questionnements sont les suivants : 
- Quel est la fréquence de mise a jour des conso via l'api. En fonction de cette fréquence ceci sera plus ou mois efficace
- Quel sera le comportement des courbes au changement de mois.  Avril arrive, on verra bien

Malheureusement il semble être assez compliqué de remonter l'historique des données. Pour l'instant je met ca de coté.

Vos retours sont bienvenus a tout point de vue.

**Comment by DomyDGJ** [comment]
Bonjour

Merci beaucoup pour votre aide.

Je ne suis pas chez moi, mais dés mon retour je fais l’installation.

Merci en core et bon weekend.

dominique

**Comment by TheGui01** [comment]
Ce n'est pas encore au point. Besoin de redémarrer HA pour avoir la remontée.
Nous n'avons qu'une mise a jour par jour que remonte les conso de la veille.
En l'etat (hors bug refresh) on a donc un decalage d'un jour.
Ca n'est pas juste mais je n'ai pas trouvé la possibilité de remonter une valeur pour un axe temps donné...

D'autre part, je pense changer ma logique et remonter le cumul total de tous les mois au lieu de ne prendre que le mois en cours : en effet en l'état on ne remontera rien le 1er jour de chaque mois.
Je regarde tt ca ce soir

**Comment by defaliz** [comment]
hello,
j'ai bien fait ma maj, aucun pb...
j'ai ajouter le capteur chauffage dans energy...
pour l'instant aucune remontée de données...ma chaudière est une PAC temao

**Comment by TheGui01** [comment]
Hello @defaliz 
Il faut attendre demain matin pour que les capteur s'incrémentent avec les conso du jour. Ce différenciel sera alors visible

**Comment by defaliz** [comment]
ok, merci beaucoup, bonne soirée

**Comment by TheGui01** [comment]
Bonjour a tous.
C'est fonctionnel !
v1.9.1 proposée & readme mis a jour : Je vous invite a regarder les  2 videos dans le readme si vous voulez remonter des conso plus précises.

**Comment by DomyDGJ** [comment]
Merci.
Je m'en occupe dès mon retour.

Bonne fin de journée.

Dominique

**Comment by Galen-Titanium** [comment]
Génial merci pour le boulot, j'essaie d'installer cela dans la soirée
