### ISSUE TITLE
Accés au mode actuel de la chaudiere en attribut d'entité

### ISSUE THREAD

**Issue by TDSnet** [TheGui01/Frisquet-connect-for-home-assistant#12]
Bonjour,
Encore bravo pour la travail.  Je ne suis pas un specialiste d'HA, je l'utilise surtout comme passerelle et travaille exclusivement en MQTT. Sur l'intégration je récupère bien les attributs, température, consigne, mode ec, mode chauffage, mais pas le status de la chaudiere (HEAT, AUTO, OFF). l'attribut "hvac_modes" retourne l'énumération , pas l'état. Est ce possible d'ajouter cet attribut ? 
Je viens de charger la nouvelle version, je recupère bien la consommation.     Merci
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/7415531/c51344e3-0870-4c51-90df-54eb210c4215)

![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/7415531/44453d72-6a5e-415f-ae0e-a8496df1f834)
Resultat en MQTT
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/7415531/98ec4f9b-414c-4b84-b6e6-d417c58cbcf6)

**Comment by TheGui01** [comment]
Bonjour @TDSnet 
C'est l'état de l'entité climate qui te retourne le mode hvac actif.
hvac_modes liste les modes existants au même titre que preset_modes.
Je ne suis pas un pro de MQTT mais il faut que tu récupère l'état de climate.maison_zone_1

**Comment by TDSnet** [comment]
Bonjour,
Ok merci, je suis passé complètement a coté… C’est parfait.  
Je teste tout cela dans la semaine, mais j’ai constaté un passage inexpliqué en mode éteint sur HA, avec obligation de redémarrer l’integration… je vais creuser. Bon week end

**Comment by TheGui01** [comment]
@TDSnet 
Ok parfait
J'ai eu le meme soucis ce matin. Je pense que c'est lié aux modifs sur la conso..

**Comment by defaliz** [comment]
bonjour,
aucune remontée chez moi pour la conso chauffage...
ou puis-je voir les logs ?
merci
