### ISSUE TITLE
pas de remontée de données de consommation

### ISSUE THREAD

**Issue by defaliz** [TheGui01/Frisquet-connect-for-home-assistant#13]
Bonsoir,
le nouveau sensor maison_consomation_chauffage ne remonte aucune donnée... ( je n'utilise pas l'eau chaude)
en ce moment la chaudière est à l'arrêt... j'imagine donc que c'est normal...
puis-je vérifier dans les logs que tout est OK ?
sinon il faudra attendre octobre prochain pour quand je remettrai le chauffage...

merci pour le taf...
ALain

**Comment by TheGui01** [comment]
Bonjour,

Rien ce matin ?
Est ce que le capteur a une valeur ou bien il est indisponible ?
Qu'en est il des consomations coté appli frisquet ?

**Comment by defaliz** [comment]
bonjour,
je n'ai pas de conso côté appli frisquet, sans doute parce que c'est une PAC :-)
je pensais que ça pourrait également fournir la conso électrique...

**Comment by defaliz** [comment]
voici ce que j'obtiens avec le curl
curl --location 'https://fcutappli.frisquet.com/api/v1/sites/xxxxxxxxxxxxxxxxxxxx/conso?token=xxxxxxxxxxxxxxxxx&types%5B%5D=CHF&types%5B%5D=SAN'

{"CHF":[],"SAN":[],"max":2000}

je devrais donc pouvoir afficher une valeur ?

**Comment by defaliz** [comment]
2kw en l'occurence...???

**Comment by TheGui01** [comment]
Non
La reponse est vide : rien entre les crochets.

**Comment by defaliz** [comment]
Bah.. donc de de données de conso pour les PAC, ou alors comme ma chaudière est arrêtée depuis 8 jours... 
Il vous savez a quoi correspond le max 2000 ?

**Comment by TheGui01** [comment]
Non vous n'aurez jamais rien.
La réponse envoie un historique.
Aucune idée pr max 2000

**Comment by defaliz** [comment]
Ah ok ..
Merci pour les réponses rapides...
