### ISSUE TITLE
Multi sites not available

### ISSUE THREAD

**Issue by ftricot** [TheGui01/Frisquet-connect-for-home-assistant#15]
For an account having several devices, only the first is accessible in HA

**Comment by TheGui01** [comment]
Hello @ftricot 

I've just published a new beta release (v2.0.0) where I tried to handle multi site.
If you click to Add device you should be able to add your second site. 
I'm really not sure it works as it's complicated for me to simulate several sites.
Please tell me if wou have errors and if not please ensure there is no mix between both devices 

Thanks

**Comment by ftricot** [comment]
Install beta Ok
Add a device : my 2 equipments are listed
I select the second one. Next screen or sats device Xxx had been added. But Xxx is the first device I already had added 
In the list of devices I have 1 device with its sensors and a second device with same name and no sensor

**Comment by ftricot** [comment]
![Screenshot_20240829_184210_Home Assistant](https://github.com/user-attachments/assets/fe9fff3c-8e60-4567-845d-7f748df3ee0c)
![Screenshot_20240829_184226_Home Assistant](https://github.com/user-attachments/assets/63afe016-6a15-480b-91e8-186d3b0063d7)
![Screenshot_20240829_184251_Home Assistant](https://github.com/user-attachments/assets/fce07f38-0231-4d77-be48-1b636416c9ca)

**Comment by TheGui01** [comment]
@ftricot are you able to click on Avtiver les enregistrements de jpurnaux, try again again then stop enregistrements des journaux ?
This will download a file
It would be great if you can share it here oaying attention your password is not visble into the log
Thanks

**Comment by ftricot** [comment]
Done. Removed password occurences
[home-assistant_frisquet_connect_2024-08-29T17-53-25.044Z.log](https://github.com/user-attachments/files/16803343/home-assistant_frisquet_connect_2024-08-29T17-53-25.044Z.log)

**Comment by TheGui01** [comment]
@ftricot work is quite huge.

I ll do my best to provode something in the next 2 weeks

**Comment by ftricot** [comment]
Tell me what I can do to help. Tests...

**Comment by TheGui01** [comment]
Bonjour @ftricot ,

Je viens de push la v2.0.1 qui devrait un peu mieux fonctionner.
Si pas d'erreur après l'ajout du 2e site ça sera déjà une victoire :).

Si victoire, pourrez vous ensuite vous assurer que : 

- les actions passée comme des changements de mode et/ou de consigne de température sont bien répliqués sur le bon site, sans impacter l'autre ?
- Les mises à jour se font sur les bons sites.

Merci !!
🤞 

Guillaume

**Comment by ftricot** [comment]
Bonjour,
Merci pour ce travail !
J'ai fait la mise à jour, supprimé une chaudière, réinstallé deux chaudières, il m'en reste une fantôme
Je vois que les indicateurs de conso sont les même dans les deux, mais je m'aperçois aussi que ma seconde chaudière est éteinte et donc non pilotable par l'appli Frisquet. Je la rallume cette après-midi et je continue les tests
PS : je devrais pouvoir tester 3 dans l'année. Le temps de connecter (si c'est possible) une autre chaudière Frisquet plus ancienne que j'ai sur un appart à Paris.
![frisquet_2_0_1_setup](https://github.com/user-attachments/assets/cbdc837a-7331-47be-915a-09db2f8c4e7f)
![frisquet-bordeaux](https://github.com/user-attachments/assets/2c4efa05-1c71-4d4f-8c96-c3ee2fcedd2b)
![frisquet-limeuil](https://github.com/user-attachments/assets/3c67b980-9b2d-4eaa-ab03-defbb2512eb2)

**Comment by TheGui01** [comment]
@ftricot 
C'est pas encore ca mais on avance !
Coté Contrôle, on voit bien des température différente a Limeuil et Bordeaux
Je regarde pour les capteurs de T° et conso
Sinon je viens de repush la v2.0.2 car aucune mise a jour ne remontait.
J'essaie d'avancer un peu cette aprem

**Comment by TheGui01** [comment]
@ftricot 
Tu pourras me faire un retour après teste de la 2.0.3 et me dire si les consos et les capteurs de températures son toujours mélangés entre les sites ?
merci

**Comment by ftricot** [comment]
![Screenshot_20240923_232647_Home Assistant](https://github.com/user-attachments/assets/bdfd9bb6-f1b7-462b-ac91-ee49fcce8b22)
![Screenshot_20240923_232658_Home Assistant](https://github.com/user-attachments/assets/d701de85-f6c6-473b-9317-71c17571a855)
![Screenshot_20240923_232709_Home Assistant](https://github.com/user-attachments/assets/42640275-6845-40b4-bf16-bd236b76c288)

Ça semble fonctionner jusque là.
J'ai des consommations différentes. 
Je testerai plus demain. 
Le seul truc bizarre c'est que lorsque j'étais en 2.0.1 ça arriverait 1.0.0 et maintenant que je suis en 2.0.3, ça affiche 2.0.1 sur l'intégration

**Comment by TheGui01** [comment]
@ftricot pour la version c'est un simple oubli de ma part 😅
Je vais corriger cela dans qq jours, quand je vais passer ceci en release non beta.
J'aimerais reussir a ne pas faire ressaisir les users mdp a l'ajout d'appareil.
Si je trouve pas rapidement je pusherai sans cela.

C'est une bonne nouvelle que cela fontionne !

**Comment by ftricot** [comment]
J'ai l'impression que la 2.0.3 remet des consos similaires sur chaque système (régression). De plus le mode water_heater est le même pour les deux aussi, alors que j'en ai un à l'arrêt.
De plus j'avais changé les identifiants des entités et ça ne fait pas comme dans d'autres intégrations, les entités se dédoublent dans ce cas.
Du coup j'essaie de tout supprimer et de tout recréer. Résultat dans le prochain post.

**Comment by ftricot** [comment]
La réinstallation c'est bien passée, les entités fantômes ont disparu.
J'ai l'impression que les datas sont rattachées au mauvais site.

![Screenshot_20240924_233026_Frisquet Connect](https://github.com/user-attachments/assets/7bc8226c-c126-40cc-bc31-b23dba88152d)
![Screenshot_20240924_233102_Frisquet Connect](https://github.com/user-attachments/assets/13838b45-041e-4bf4-ad9e-8f734e302717)

![Screenshot_20240924_233047_Frisquet Connect](https://github.com/user-attachments/assets/74a62b0a-b7a5-4a5a-bd99-866b2597594a)
![Screenshot_20240924_233017_Frisquet Connect](https://github.com/user-attachments/assets/6f62f015-5376-45d0-b7b7-68198b6612dc)
![bordeaux-ha](https://github.com/user-attachments/assets/ec837312-45af-4155-bc05-0a1564b9c9cf)
![limeuil-ha](https://github.com/user-attachments/assets/7109bd33-b3b0-4f91-a84b-589f7739a18a)
Mon site Bordeaux (j'en suis absent) est avec un chauffe-eau arrêté (Mode stop), ça apparaît bien dans l'appli Frisquet, et sous Limeuil dans Home Assistant.

**Comment by ftricot** [comment]
Bon, je ne sais pas si je m'étais trompé de version, mais en retelechargeant la 2.0.3 je ne constate plus les problèmes de données mal affectées

**Comment by ftricot** [comment]
PS : j'ai l'impression qu'à la création initiale d'un appareil ça collecte les bonnes données et qu'ensuite à la mise à jour ça fasse les inversions. En effet, hier soir je pensais crier victoire, mais quand je suis retourné sur mon tableau de bord, je me dis que non.

**Comment by TheGui01** [comment]
Hello @ftricot 
Je vais essayer de regarder tout ca aujourd'hui

**Comment by ftricot** [comment]
En fait ça oscille tout seul. 

![frisquet-flickering](https://github.com/user-attachments/assets/de1c4e09-136d-4852-855c-67636db824f0)

**Comment by TheGui01** [comment]
@ftricot 
Je viens de push une nouvelle version.
J'avoue que c'est compliqué. Je suis un peu a l'aveugle sans pouvoir tester sur un compte  multisite.
J)espère que cette version sera plu solide 🤞 
J'ai aussi ajuster l'ID pour le chauffe eau. Il faut supprimer les devices pour que ca soit pris en compte

**Comment by ftricot** [comment]
C'est quoi ton email ?

**Comment by TheGui01** [comment]
> C'est quoi ton email ?
@ftricot 
Guillaume.sourd@gmail.com

**Comment by TheGui01** [comment]
@ftricot it's finally solved !!

**Comment by ftricot** [comment]
Impressive refactoring of the code to manage these edge cases. Soon will have 3 Frisquet boilers & heaters and will be able to manage them in coordination with the house status ! thanks a lot.
