### ISSUE TITLE
Intégration présente une erreur "échec de la configuration"

### ISSUE THREAD

**Issue by SMA78** [TheGui01/Frisquet-connect-for-home-assistant#17]
Bonjour,
tout d'abord un grand bravo pour ce travail d'intégration Frisquet, je n'en ai pas cru mes yeux quand je l'ai vue, je l'attendais depuis si longtemps ;)
Malheureusement j'ai un souci : après l'intégration via HACS et l'installation (login + mdp) le process se déroule sans pb (ajout de l'intégration dans HA) mais une erreur apparaît à ce moment : échec de la configuration, aucun appareil, aucune entité n'est créée.
Voici le log en pièce jointe.
Info : je n'ai pas de SSL installé, c'est peut-être une des raisons.

Ma config : HA v2024.8.2 sur raspberry pi 4, réseau local uniquement, freebox révolution, zigbee

A ta disposition pour des compléments si besoin.

[Logs Frisquet.txt](https://github.com/user-attachments/files/16737761/Logs.Frisquet.txt)

**Comment by TheGui01** [comment]
Bonjour @SMA78 ,

A tout hasard est ce que tu ne serais pas derrière un vpn ?
Je pense que ca pourrait être la cause du soucis.

**Comment by SMA78** [comment]
Bonjour @TheGui01,Effectivement en passant par mon smartphone plus de souci. J'ai relancé le téléchargement puis relancé HA et je retrouve les 5 entités de ma chaudière. Problème résolu grâce à toi. Petite remarque au passage si tu fais une mise à jour : le titre affiché est Frisquest au lieu de Frisquet. Et les 2 entités "consommation" sont écrites avec un seul m.Encore merci !Le 25 août 2024 12:14, TheGui01 ***@***.***> a écrit :
Bonjour @SMA78 ,
A tout hasard est ce que tu ne serais pas derrière un vpn ?
Je pense que ca pourrait être la cause du soucis.

**Comment by TheGui01** [comment]
Super !
Merci pour les remarques sur les typos.
Jevais corriger ca !
Une mise a jour beta devrait arricer en fin de semaine pour la gestions des multi sites 🤞

**Comment by TheGui01** [comment]
@SMA78 
Pour info, la beta v2.0 corrige les fautes.
Cette version semble stable... a voir... 😉

**Comment by SMA78** [comment]
@TheGui01 
Je suis très curieux...et le fait que tu aies réussi à créer l'intégration Frisquet m'amène à te poser une question ?
En effet, les installateurs de chaudière avec qui j'ai échangé m'ont toujours dit que cela n'existait pas, Frisquet garde ses accès privés, le patron de Frisquet n'est pas fan de domotique, etc. 
Donc quel est ton secret pour avoir réussi à créer cette intégration ? Comment as-tu trouvé à intercepter les messages avec la chaudière ?
De plus je possède une alarme de chez SEPTAM, modèle Harmonia pour laquelle mon installateur me fait le même type de réponse. Peut-on imaginer que ce type d'alarme soit intégrée un jour aussi ?

Merci pour ta réponse (si tu trouves du temps pour me répondre) ;)

**Comment by TheGui01** [comment]
Hello @SMA78 ,

Pour pouvoir récupérer une API, il faut utiliser un outil de capture SSL qui va jouer le "man in the middle" entre l'app et le serveur.
L'outil le plus connu est proxyman qui fonctionne sous Apple.
Je n'ai pas fait ce travail mais un membre de la communauté Jeedom m'a partagé le détail de l'API.

Pour les remarques de tes differents installeurs : 
Je dirais qu'aucun fabricant ne souhaite qu'on requete sur ses serveurs avec des développements maison pas forcément bien designé et qui peuvent surcharger leurs serveurs. 
Quant a développer eux-mêmes leur intégration pour les différentes solution domotiques, je pense que cela ne leur apporte pas de valeur ajouté. Ca reste un marché de niche.

Enfin pour ton alarme, tu peux veiller et peut etre qu'un courageux développera le necessaire pour !
