### ISSUE TITLE
Entité chauffe-eau with PAC

### ISSUE THREAD

**Issue by Pierret-ha** [TheGui01/Frisquet-connect-for-home-assistant#18]
Bonjour, voici le problème de l'intégration du chauffe-eau : 
```
Enregistreur: homeassistant.components.water_heater
Source: helpers/entity_platform.py:361
intégration: Water Heater (documentation, problèmes)
S'est produit pour la première fois: 08:55:15 (1 occurrences)
Dernier enregistrement: 08:55:15

Error while setting up frisquet_connect platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/frisquet_connect/water_heater.py", line 26, in async_setup_entry
    entity = FrisquetWaterHeater(entry,coordinator.my_api,"ecs")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/water_heater.py", line 52, in __init__
    self.current_operation =  self.FrisquetToOperation(coordinator.data["ecs"]["MODE_ECS"]["id"])
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by TheGui01** [comment]
Bonjour @Pierret-ha 

Merci !
Il faudrait que tu actices les logs pour que je puisse avoir le retour de l'API.
Le fait que tu aies un chauffe eau solaire a l'air de changer la structure de la réponse.

Je suis au bureau je t'explique comment activer les logs ASAP

**Comment by Pierret-ha** [comment]
Rebonjour :p Le chauffe-eau n'est pas solaire. C'est une PAC avec le ballon externe. LA pac date de 2019, c'est une Theamo 8 kW (code article F7AB00000)

**Comment by Pierret-ha** [comment]
Voici le document.

[home-assistant_frisquet_connect_2024-10-01T13-00-55.002Z.log](https://github.com/user-attachments/files/17209966/home-assistant_frisquet_connect_2024-10-01T13-00-55.002Z.log)

**Comment by TheGui01** [comment]
Merci @Pierret-ha !
Pourrais tu s'il te plait passer ton chauffe eau en off et refaire un log ? J'aurais ainsi les id pour on et pour off.
Ensuite il va me falloir un peu de temps car je dois terminer le multi-site avant :)
Mais ce sera fait ASAP !

**Comment by Pierret-ha** [comment]
Salut @TheGui01, voici les logs avec le chauffe-eau OFF. 
J'espère que c'est ce qu'il te faut :) si il y a quoi que ce soit hésites pas. Je ne sais pas comment je peux t'aider mais si je peux faire quelque chose :p 
[home-assistant_frisquet_connect_2024-10-02T13-54-10.043Z.log](https://github.com/user-attachments/files/17247070/home-assistant_frisquet_connect_2024-10-02T13-54-10.043Z.log)

**Comment by TheGui01** [comment]
Salut@Pierret-ha 
La derniere version beta v2.0.13 pourrait peut etre fonctionner
Tu peux tester ?

**Comment by Pierret-ha** [comment]
Salut @TheGui01, merci beaucoup tout fonctionne ! T'es un champion !!!
(désolé de pas avoir répondu avant, bcp de travail...) Merci encore !

**Comment by TheGui01** [comment]
Salut @Pierret-ha 

Spuer nouvelle !
Je clos le ticket

**Comment by Pierret-ha** [comment]
Salut @TheGui01, bon, le chauffe eau apparaît sur l'intégration, elle reçoit les données ON et OFF (seulement quand je redémarre HA). Par contre elle ne peut pas appeler le service. J'ai essayé de m'aider avec chatgpt mais il n'a pas ton talent ;), pourrais tu voir ce que tu peux faire stp ? Merci d'avance ! et n'hésites pas à me dire ce que tu veux que je te donne pour aider :)

**Comment by TheGui01** [comment]
Hello @Pierret-ha 
Est ce que tu peux check.si tu as des logs d erreurs quand tu appelles le service ?
Ue veuw tu dire par appeler le service? C est quand tu changes de ON a OFF ?

**Comment by TheGui01** [comment]
@Pierret-ha  c est bon je vois ce qui manque

**Comment by TheGui01** [comment]
Bonjour  @Pierret-ha 
En fait tu peux deja créer une automation, mais il faut passer en mode yaml. Voici un exemple. Tu crées une nouvelle automatisation, puis tu cliques sur les 3 points en haut a droite → Modifier en Yaml et du tappes ca :
`alias: Test Chauffe eau off
description: Test Chauffe eau
triggers: []
conditions: []
actions:
  - action: water_heater.set_operation_mode
    target:
      entity_id: water_heater.chauffe_eau
    data:
      operation_mode: Off
mode: single
`
operation_mode: On pour l'autre cas
Ensuite tu peux reswitch en non Yaml pour ajuster tes triggers conditions. 
Je vais essayer de prendre en charge le service Allumer/Eteindre mais pour les chaudiere a Gaz "On"  n'existe pas. Je vais voir ce que je propose...

**Comment by Pierret-ha** [comment]
![Capture d'écran 2024-10-09 165641](https://github.com/user-attachments/assets/e2ce0c55-4fa6-4d0e-b066-a427cab3cf7d)
Merci @TheGui01 pour ta réponse, je t'ai mis la capture d'écran avec le message d'erreur. J'ai vu que tu as fait une maj il y a 1h, je l'ai téléchargée. La fonction ne passe toujours pas.

**Comment by TheGui01** [comment]
@Pierret-ha 
Je viens de réparer une coquille... désolé.
Tu peux ressayer ? Je ne suis pas sûr que ca sera ok pour toi car mon message était un peu différent.

**Comment by Pierret-ha** [comment]
T'as pas à être désolé ;) . Mais non ça ne marche pas :/

**Comment by TheGui01** [comment]
@Pierret-ha arrives tu a activer les logs et effectuer l'action qui plante, puis a poster ca ici ?
Merci

**Comment by TheGui01** [comment]
attends j'ai reproduit !

**Comment by TheGui01** [comment]
@Pierret-ha v2.1.2 devrait fonctionner 🤞

**Comment by Pierret-ha** [comment]
Bonjour @TheGui01, je te confirme que j'ai les infos de la passerelle qui remontent, en revanche quand il s'agit de faire une action Stop et On, la passerelle ne réagit pas.

**Comment by TheGui01** [comment]
Hello @Pierret-ha 
My bad ! Effectivement, ca ne marche plus non plus pour moi.

Je regarde cette semaine

**Comment by Pierret-ha** [comment]
![Capture d'écran 2024-11-05 090107](https://github.com/user-attachments/assets/bf26ee4a-a6ed-4dff-9730-1522ea2ca3c7)
Bonjour, je t'ai mis la capture d'écran, j'utilise bien set operation mode. 
Sur HA quand je change pour Stop. La passerelle ne change pas son état et renvoie son état de fonctionnement (On). 
Je peux aussi changer l'état de la passerelle sur l'application Frisquet et l'état va bien remonter sur HA. C'est l'action de HA vers la passerelle qui ne fonctionne pas.

**Comment by Pierret-ha** [comment]
Pour te donner plus de précision, quand je change l'état sur HA, l'état ne change pas sur l'application frisquet. A l'inverse quand je change l'état sur l'application Frisquet, 2 minutes après, l'état change sur HA. J'espère mes explications sont compréhensibles :p

**Comment by TheGui01** [comment]
Salut @Pierret-ha 
Oui c'est tout clair.
Arrives tu as activer les logs et a me les envoyer ici apres avoir fait quelques demandes de changement de mode et une attente de 5 minimum ?

**Comment by Pierret-ha** [comment]
Salut, avec la mise à jour 2.1.6, ça semble avoir résolu le problème. L'état change bien sur la passerelle. Je te tiens au courant si je vois des erreurs. Je surveille ça de près :).

**Comment by TheGui01** [comment]
Salut @Pierret-ha 
C'est top !
Je te conseille de passer en 2.1.7 release hier soir
