### ISSUE TITLE
Maj ?

### ISSUE THREAD

**Issue by defaliz** [TheGui01/Frisquet-connect-for-home-assistant#19]
Bonjour,
Est ce nécessaire de faire les mises a jour si l'on a qu'un seul site ?
Merci

**Comment by TheGui01** [comment]
Bonjour @defaliz ,
Non ce n'est pas nécessaire d'autant plus que ce n'est pas encore 100% finalisé, il y a quelques petit bugs.
Une fois que tout sera 100% finalisé, je publierai une version non beta et tu pourras l'installer histoire d'être à jour

**Comment by defaliz** [comment]
très bien, merci pour ta réponse rapide...
