### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by JC38** [TheGui01/Frisquet-connect-for-home-assistant#2]
Bonsoir,

Je viens d'essayer cette intégration mais ça plante...
Voici le détail de l'erreur
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 10:19:18 PM (2 occurrences)
Last logged: 10:21:16 PM

Error setting up entry Maison for frisquet_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/__init__.py", line 20, in async_setup_entry
    await my_api.getTokenAndInfo(entry.data["zone1"],idx)
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 81, in getTokenAndInfo
    else: return self.data[idx]
                 ~~~~~~~~~^^^^^
KeyError: 'radiateurs'

**Comment by TheGui01** [comment]
Salut,

Est ce que tu arriverais a activer le debogage et m'envoyer la ligne "In
PoilFrisquetAPI response :
J'ai l'impression qu'on a pas le meme type d'install et donc une reponse
assez différente de l'API

**Comment by TheGui01** [comment]
@JC38 ,
Je viens de push un fix, j'ai trouvé un reliquat inutile.
Ca devrait marcher.
Peux tu tester et me faire un retour ?
J'attends ton retour pour clôturer

**Comment by Amapem** [comment]
même type d'erreur chez moi

2024-01-16 23:05:33.923 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Maison Ledru-Rollin for frisquet_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/__init__.py", line 20, in async_setup_entry
    await my_api.getTokenAndInfo(entry.data["zone1"],idx)
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 81, in getTokenAndInfo
    else: return self.data[idx]
                 ~~~~~~~~~^^^^^
KeyError: 'zonemaison'

**Comment by TheGui01** [comment]
Bonjour @Amapem 
J'ai publié hier sor un nouveau fichier __init__.py.
As tu essayé avec cette version?
Je n'ai pas publié de release encore, j'attend vos retours.

Merrci,
Cdt,
Guillaume

**Comment by JC38** [comment]
Bonjour
J'ai réinstallé l'intégration, ce qui a du forcer la maj du fichier.

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 8:30:08 AM (2 occurrences)
Last logged: 8:52:28 AM

Error setting up entry Maison for frisquet_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/__init__.py", line 20, in async_setup_entry
    await my_api.getTokenAndInfo(entry.data["zone1"],idx)
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 81, in getTokenAndInfo
    else: return self.data[idx]
                 ~~~~~~~~~^^^^^
KeyError: 'radiateurs'

Tu aurais pas écrit des trucs "en dur" comme le nom des zones ?
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/16527222/711ad78e-e8a0-493f-befb-9a3ff5573226)

**Comment by Amapem** [comment]
C'est ok avec la 1.6.4
Merci

**Comment by TheGui01** [comment]
Merci pour le feedback !
J'ai encore parfois un plantage la nuit qui necessite un reboot de HA.
Je veille et republierai des fixs dès que je trouve la root cause

**Comment by JC38** [comment]
Yep. Thanks
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/16527222/2b87b528-d7e9-4088-b407-c1d2342517d7)

**Comment by JC38** [comment]
Gloups. Ne ferme pas le ticket de suite. Je viens de renommer le device et pour l'instant, c'est pas top
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/16527222/f44c4559-ff77-44a0-abfe-df4c8b945936)

**Comment by TheGui01** [comment]
@JC38 ,
Confirmes tu que tu fais l'opération suivante ?
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/99127784/4882f6f7-f960-4d56-8d82-9b6800150188)

Pour moi ce n'est pas lié au problème initial. Donc je ne réouvre pas le ticket.
Je regarderai ce point dans la semaine

**Comment by JC38** [comment]
Oui, j'ai modifié Maison en chaudière et accepter les autres changements de rename qu'il propose. Je vais supprimer le device et le recréer. Et pas le renommer en attendant ton feedback.

**Comment by TheGui01** [comment]
@JC38 je vois aussi une erreur sur un des capteurs de température. En effet la meme T° remonte pour le plancher et les radiateurs
Tu confirmes l'erreur?
J'ai une idée pr ajuster

**Comment by TheGui01** [comment]
@JC38 
Je ne parviens pas à reproduire l'erreur sur mon serveur de test.
Le changement de nom de device ne désactive aucune Entité. Je n'ai en revanche aucune proposition de changement associé.
As tu des automatisation lié aux entités ?
Pour quelle raison souhaites tu renommer le device ? N'est-il pas approprié de modifier son nom sur Lovelace ? Les tuiles lovelace permettent de renommer tes éléments sans toucher au IDs des intégrations

**Comment by JC38** [comment]
Pour les températures, le 2 Sensors sont effectivement identiques.
Pour le rename, il reprend le nom depuis le www de Frisquet.
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/16527222/15bfd717-6095-4243-9c99-2e137da1367b)
Que sur le portail, on parle de site et qu'on l'appelle Maison, pas de souci. Mais côté HA, ce n'est qu'un device parmi d'autres, en l'occurence 1 chaudière située dans une pièce de ... la maison, j'ai juste essayé de l'appeler Chaudière dans HA. Je verrai pour refaire le test ce soir et prendre des screenshots.

**Comment by TheGui01** [comment]
@JC38 je viens de push une nouvelle version pour le 2e sensor.
Pour le naming, effectivement je reprend le nom du site pour le device.
Et le nom des zones pour les entités.

**Comment by JC38** [comment]
C'est ok pour les Temp.
Je retente le rename avec les captures
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/16527222/5f343a84-242d-4803-a632-e66c055d5a18)
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/16527222/fe06073c-8f96-44d2-8943-db8ce2e6d9f7)
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/16527222/d8b923bf-5393-4fa0-b88b-8d3ed373d232)
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/16527222/8309a17b-7caf-4e60-b96e-084f8fb3379b)
Et voili, c'est cassé

**Comment by JC38** [comment]
C'est remonté correctement au niveau affichage après un certain temps, je pense qu'il faut attendre un refresh des valeurs pour que l'affichage redevienne correct.

**Comment by TheGui01** [comment]
A mon avis c'est un pb de cache navigateur. Pour que ca aille plus vite tu
fais CTRL + F5 pour rafraîchir et ca va vider le cache.
Bonne nouvelle en ts cas !
