### ISSUE TITLE
après changement d'ip de la box frisquet, plus de relève sur HA

### ISSUE THREAD

**Issue by defaliz** [TheGui01/Frisquet-connect-for-home-assistant#21]
bonjour
ma box frisquet a changé d'ip, elle est bien sur le réseau et l'app frisquet fonctionne bien
côté HA voici les erreurs du log : Error setting up entry Maison for frisquet_connect

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1068, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1149, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

merci pour l'aide...
Alain

**Comment by TheGui01** [comment]
Bonjour @defaliz 
Les changements fait en local n'ont aucun impact sur mon intégration qui ne communique qu'avec les serveurs Frisquet.

Est ce que vous avez les remontés sur l'app officielle ?

**Comment by defaliz** [comment]
oui sur l'app tout fonctionne,
je suis en version 1.0.0
peut être dois-je désinsaller et réinstaller ?

**Comment by TheGui01** [comment]
@defaliz oui vous pouvez tenter.
Intallez la dernière version, ca ne fera pas de mal

**Comment by defaliz** [comment]
Après mise à jour, tout refonctionne...
merci et bonne journée
