### ISSUE TITLE
Comment savoir si le boitier `Frisquet Connect` est bien connecté à Internet ?

### ISSUE THREAD

**Issue by brunohead** [TheGui01/Frisquet-connect-for-home-assistant#22]
Bonjour,

et merci pour cette extension, beau travail! J'étais sur Domoticz et now sur HA c'est incroyable de voir tout ce qui existe comme add-ons.

Ma question est la suivante:

* Existe-t-il un moyen, comme sur l'App mobile `Frisquet Connect` de savoir si le boitier est bien relié à Internet ?

Le cas échéant, les serveurs Frisquet ne sont pas au courant des mises à jour. Ce qui a pour conséquence d'afficher des informations erronées (_comme sur l'App mobile_) sur notre dashboard.

Sur l'App mobile, il y a cette information.

Merci d'avance pour votre retour.

**Comment by TheGui01** [comment]
Bonjour @brunohead 

Pouvez-vous m'indiquer ou vous trouvez cette information sur l'appli ?
Un screenshot serait bienvenue

Merci
Guillaume

**Comment by brunohead** [comment]
Bien sûr:

Sur le 1er screenshot, ce n'est qu'une **pastille rouge** qui le montre
![image](https://github.com/user-attachments/assets/d3191cad-13af-4d0c-88b2-050411ac7ea2)

Sur le 2ème, c'est une alerte:
![image](https://github.com/user-attachments/assets/2bf6f4b9-47a8-42ad-a3be-c63226473843)

- Est-ce que l'API de Frisquet renvoie cette information ?

**Comment by TheGui01** [comment]
@brunohead merci !
Je regarde ca dans la semaine.
Si l'alerte est récupérable, j'essayerai de créer un capteur pour cela

**Comment by TheGui01** [comment]
@brunohead ca arrive ! Je teste ca encore qq jours et publierai une release mercredi je pense 
Il faudra certainement supprimer ses appareil et les recréer.

**Comment by brunohead** [comment]
Super, merci bcp pour cette réactivité 😅.

**Comment by TheGui01** [comment]
Hello @brunohead 
J'ai publish la v2.1.6 pour ta demande. Attention il faut ensuite supprimer ton device et te reconnecter.

**Comment by brunohead** [comment]
Merci bcp la nouvelle release ! Cela fonctionne à merveille 😉 

![image](https://github.com/user-attachments/assets/5ae1cfa7-1351-43dc-89ba-ba17c1a03e9a)
