### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by fjumeaux** [TheGui01/Frisquet-connect-for-home-assistant#23]
Enregistreur: homeassistant.util.loop
Source: util/loop.py:136
S'est produit pour la première fois: 12:23:07 (1 occurrences)
Dernier enregistrement: 12:23:07

Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'frisquet_connect' at custom_components/frisquet_connect/climate.py, line 360: desired_timezone = pytz.timezone(self.tz) (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/TheGui01/Friquest-connect-for-home-assistant/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/frisquet_connect/__init__.py", line 36, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2121, in async_forward_entry_setups await self._async_forward_entry_setups_locked(entry, platforms) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2132, in _async_forward_entry_setups_locked await asyncio.gather( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2134, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2214, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in async_setup_entry return await component.async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 328, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/frisquet_connect/climate.py", line 58, in async_setup_entry entity = FrisquetConnectEntity( File "/config/custom_components/frisquet_connect/climate.py", line 157, in __init__ self._attr_preset_mode = self.defPreset( File "/config/custom_components/frisquet_connect/climate.py", line 316, in defPreset return self.getPresetFromProgramation() File "/config/custom_components/frisquet_connect/climate.py", line 360, in getPresetFromProgramation desired_timezone = pytz.timezone(self.tz)

**Comment by TheGui01** [comment]
@fjumeaux 
Please uninstall and install integration again

**Comment by fjumeaux** [comment]
Aie 

Always the same problem

Enregistreur: homeassistant.util.loop
Source: util/loop.py:136
S'est produit pour la première fois: 15:09:03 (1 occurrences)
Dernier enregistrement: 15:09:03

Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'frisquet_connect' at custom_components/frisquet_connect/climate.py, line 360: desired_timezone = pytz.timezone(self.tz) (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/TheGui01/Friquest-connect-for-home-assistant/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/frisquet_connect/__init__.py", line 36, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2255, in async_forward_entry_setups await self._async_forward_entry_setups_locked(entry, platforms) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2266, in _async_forward_entry_setups_locked await asyncio.gather( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2268, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2348, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 228, in async_setup_entry return await hass.data[DATA_COMPONENT].async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 197, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 332, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/frisquet_connect/climate.py", line 58, in async_setup_entry entity = FrisquetConnectEntity( File "/config/custom_components/frisquet_connect/climate.py", line 157, in __init__ self._attr_preset_mode = self.defPreset( File "/config/custom_components/frisquet_connect/climate.py", line 316, in defPreset return self.getPresetFromProgramation() File "/config/custom_components/frisquet_connect/climate.py", line 360, in getPresetFromProgramation desired_timezone = pytz.timezone(self.tz)

**Comment by TheGui01** [comment]
Bonjour!

**Comment by TheGui01** [comment]
Ah merci @fjumeaux  😀
Effectivement la 2.1.7 affiche toujours 2.1.6 jai oublie de mettre un fichier a jour.

Est ce que vous avez une fonctionnalité qui est impacté par ce warning ?

Il me semble que tout est fonctionnel malgré cela : c'est pytz qui remonte cela : ceci permet de récupérer l'heure exacte en fonctione de votre fuseau horaire pour récupérer correctement le mode (comfort /reduit) selon la programmation en place.

Si vos température consigne changent au bon moment, en accord avec votre programmation, alors il n'y a pas de problème.

J essairai de trouver un alternative à pytz prochainement

**Comment by fjumeaux** [comment]
Non ce c'est pas bloquant. Je fais mes premiers pas sur HA et je n'avais pas vu ces messages jusqu'à ce que je fréquente plus souvent les journaux (je suis en train de montant un envoi de messages autodiscover vers domoticz et j'ai quelques messages d'erreurs).

Je me demandais, dans les entités que le plugin met à disposition, je n'ai pas la température de consigne de la chaudière. Je peux la modifier via la carte thermostat mais il n'y a pas d'entité accessible indépendamment. C'est normal ?

**Comment by TheGui01** [comment]
@fjumeaux 
La température de consogne est un attribut du thermostat (entité climate)
Tu peux facilement créer un template pour le récupérer.
J'ai aussi vu passer un repo sur HACS appelé Attribute as Sensor qui doit te permettre de le faire facilement
Ci dessous voici ou tu peux récupérer facilement le detail des attributs d'une entité, via Outil de développement -> Etats :
![Screenshot_20241109_191246_Home Assistant.jpg](https://github.com/user-attachments/assets/4ac33cf5-953a-41fc-ba62-5e0dbbe7b62a)

Cdt
Guillaume

**Comment by fjumeaux** [comment]
Ok ok. Parfait alors. Et donc je pourrais facilement modifier l'attribut depuis un script domoticz qui modifie un sensor de HA. Ben c'est pile ce qu'il me faut. Merci beaucoup

**Comment by TheGui01** [comment]
@fjumeaux 
Les méthodes évoquées ne permettent pas de modifier la valeur. C est juste pour la lire.

Pour la modifier, il faudra passer par une automatisation. L'inconvénient c est que ca ne pourra pas être dynamique 
Ou via l'interface manuellement.

Il faut passer sur HA et quitter domoticz 😉

Cdt
Guillaume
