### ISSUE TITLE
ECS

### ISSUE THREAD

**Issue by Pierret-ha** [TheGui01/Frisquet-connect-for-home-assistant#24]
Salut, 
Après plusieurs jours de test, j'en ai conclu que le fonctionnement de la passerelle est aléatoire et je ne sais pas pourquoi. 
Quand je met en Stop ou en On, il arrive que la passerelle renvoi son état de fonctionnement et sous HA ca repasse sur l'état du chauffe eau. 
[home-assistant_frisquet_connect_2024-11-20T15-27-59.803Z.log](https://github.com/user-attachments/files/17833391/home-assistant_frisquet_connect_2024-11-20T15-27-59.803Z.log)
J'ai fais quelques manipulations qui ont échouées en pièce jointes dans le fichier log. Desolé de te redéranger et de recréer une issue pour ça ... :/

**Comment by TheGui01** [comment]
Salut @Pierret-ha 
Lors de tes manips, est ce que tu verifies que dans l'appli nativr frisquet ton changement est pris en compte ?
Car sous HA, j'envoie la demandes aux serveurs et supposant qu'elle est prise en compte, je change l'état sous HA. Si l'état switche dans les 5 min c'est que la demande n'a pas été prise en compte.

**Comment by Pierret-ha** [comment]
Si ça a déjà fonctionné. Mais c'est très aléatoire. Ça dépend des jours et de l'heure. J'ai deux plages d'heures creuses. Mon automatisation fonctionne parfaitement. C'est vraiment entre la passerelle et HA. En revanche quand je met directement la consigne manuellement sur la passerelle ça marche très bien

**Comment by Pierret-ha** [comment]
D'après chatgpt, c'est ça qui pose problème : `In OrderToFrisquetAPI resp :'{'message': 'Authentication `failure'}`
 D'après ce qu'il me dit, ce serait un problème de renouvellement de jeton a cause du nombre de requête (J'ai 4 requête par jours et au bout de 4-5 jours ca ne fonctionne plus) . Je pense c'est une piste à suivre parce que que suite à ça j'ai désinstallé et réinstallé l'intégration et ca repart.  Set operation mode remarche :)

**Comment by TheGui01** [comment]
Hello @Pierret-ha 
Faut que je regarde, ca m'étonne...
Normalement, le token est actualisé toutes les 5 minutes
Je suis en déplacement jusque dimanche, je regarde semaine prochaine

**Comment by TheGui01** [comment]
@Pierret-ha tu as raison ! Je reproduis le problème.
A mon avis un simple reboot permet de rafraîchir le token.
J'analyse le probleme ASAP

**Comment by TheGui01** [comment]
Salut @Pierret-ha ,
Je viens de pousser une modif sur le fichier [water_heater.py](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/blob/main/custom_components/frisquet_connect/water_heater.py)
Si tu sais comment le mettre a jour, sans nouvelle version HACS, ca serait cool que tu puisses le tester.
Je viens de l'installer de mon coté. D'ici 24h, si j'arrive à passer des commandes à mon chauffe eau, alors on pourra dire que le fix est OK. Je ferais alors une nouvelle version

**Comment by Pierret-ha** [comment]
Salut, je viens de voir ton message, j'essaie demain avec le nouveau fichier et je te dis ça. Par contre si c'est OK je pourrais te dire que dans 48h, il faut que je le laisse tourner pour voir si il n'y a pas d'expiration de tokens

**Comment by Pierret-ha** [comment]
Mais oui je te confirme que la seule manip aujourd'hui est de de s'installer et réinstaller l'intégration.

**Comment by TheGui01** [comment]
@Pierret-ha 
la V2.1.8 est dispo et me semble bien régler le problème
