### ISSUE TITLE
Incohérence énergie / Suivi consommation

### ISSUE THREAD

**Issue by eflye** [TheGui01/Frisquet-connect-for-home-assistant#26]
Bonjour, @TheGui01 , tout d'abord merci pour ton travail sur ce module, il apporte beaucoup de possibilités pour avoir un fonctionnement de chauffage beaucoup plus efficace en le combinant avec https://github.com/jmcollin78/versatile_thermostat par exemple.

J'ai par contre une incohérence sur la partie énergie, suis je le seul?

Voici ma configuration:  
<img width="342" alt="image" src="https://github.com/user-attachments/assets/97c5465c-aa7f-408e-9b5f-3102f3bb930d" style="border: 2px solid black; border-radius: 5px;">. 
<img width="380" alt="image" src="https://github.com/user-attachments/assets/e9f1826d-04ee-484f-adba-59b77a2e04bf" style="border: 2px solid black; border-radius: 5px;">. 

J'ai la même somme de consommation en negatif et vu en "consommation non suivi" que la somme des 2 entités de gaz. Une idée de la raison de cette incohérence?

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/90afa27d-4c7e-4a25-bc39-d578292067bc">

**Comment by TheGui01** [comment]
Bonjour @eflye ,

C'est un sujet qui semble faire beaucoup parner sur les forums. Ce n'est pas lié directement a cette intégration mais à la nouvelle fonctionnalité de consommation non suivie qui tout le monde peine a comprendre.
Je me permet de clôturer le sujet en attendant que le sujet soit plus étayer.
Si une solution simple a implémenter dans mon code se fait connaître, je n'hésiterai pas a l'implémenter.

En attendant, on peut cliquer sur la legende pour ne plus afficher cette consommation non suivi.

Merci pour ta compréhension.
Cdt,
Guillaume
