### ISSUE TITLE
Mise à jour de l'entité climate après un envoi d'ordre

### ISSUE THREAD

**Issue by pafnow** [TheGui01/Frisquet-connect-for-home-assistant#28]
Bonjour,
Merci pour la super intégration, c'est vraiment très utile pour optimiser la chauffe et faire des économies !

J'ai remarqué que quand j'envoyais une commande via l'action  `climate.set_temperature`, la mise à jour de l'entité climate introduite par cette intégration n'est pas faite avant la prochaine requete programmée toutes les 5 minutes.
Serait-il imaginable de programmer une mise à jour plus rapide après l'envoi d'une telle commande ?

**Comment by TheGui01** [comment]
Salut @pafnow ,
Effectivement il y a un petit bug...
Je n'ai jamais utilisé d'automatisation pour changer la température cible.
Je le fais a la main et ca marche bien 
Je regarde ce week end pour ajuster cela

**Comment by eflye** [comment]
je confirme avoir le même comportement.
J'utilise ton intégration en complément de https://github.com/jmcollin78/versatile_thermostat/ + des tetes thermostatique connectés,  qui me permet de ne plus utiliser le thermostat de la chaudière pour déclencher chauffe / stop mais de me baser sur les sondes de température de mes pièces.

**Comment by TheGui01** [comment]
Salut @pafnow @eflye 
Le bug est corrigé dans la version 2.1.9

**Comment by pafnow** [comment]
Merci pour la réactivité 
Bon weekend
