### ISSUE TITLE
Changer temperature confort en mode auto reduit

### ISSUE THREAD

**Issue by pafnow** [TheGui01/Frisquet-connect-for-home-assistant#29]
Bonjour,
C'est encore moi, avec une nouvelle demande.

J'aimerais changer la température de confort pendant la nuit quand un évènement se passe. La nuit je suis en reduit mais je souhaite changer la température confort pour que le matin quand le mode auto repassera sur le confort la température soit changée.

Via l'appli Frisquet c'est très simple à faire, via le menu Réglages/ Chauffage mais je n'ai pas trouvé d'équivalent via l'intégration.
En fait jai meme fait une boulette en remontant la température reduit sans reflechir :)

**Comment by TheGui01** [comment]
@pafnow 
Ce n'est pas possible effectivement.
Je me suis pas mal creuser la tête pour avoir un mode de fonctionnement compatible avec les possibilités qu'offre HA.
Si vraiment tu souhaites faire ce type de changement, il faudrait séquencer plusieurs actions :
1 - Passer en confort : Faire sauter la dérogation en repassant en auto
2 - Ajuster la température cilble
3 - Repasser en reduit


Toutefois, je m'interroge sur l'utilité de changer les températures cibles ?
Pour un usage quotidien, il est recommandé de ne pas avoir un ecart de plus de 3 degrés entre les modes confort et réduits. Au dela les économies ne se font plus.

Enfin, je ne vois pas de cas pratique où je souhaiterais changer de température confort ? Je souhaite avoir chaud le matin au reveil, ceci toujours a la meme température ? 
Le besoin ne serait pas plutot d'ajuster l'heure de passage a confort, pour un reveil avancé ou reculé ? Peut etre voir si ceci pourrait aider ?

**Comment by pafnow** [comment]
> Je me suis pas mal creuser la tête pour avoir un mode de fonctionnement compatible avec les possibilités qu'offre HA.

Oui j'imagine, quand je lis le descriptif de comment fonctionne l'entité climate introduite par cette intégration, on comprend que ça n'a pas dû être simple du tout.

Pour donner plus de contexte, mon besoin vient du fait que les chambres sont sous combles et que parfois, on déplace le thermostat radio des pièces de vie dans la partie chambre, la nuit en particulier.
J'ai mis une balise sur le thermostat qui me permet de le localiser dans la maison et agir en fonction sur l'extinction/allumage de certains radiateurs.
Ma température confort idéale est de 19.5 degrés en journée mais quand le thermostat est dans les chambres et que la chauffre reprend le matin, ca fait un sacré pic qui monte parfois à 20.5 voir 21.
Redescendre un peu la température confort la nuit permet de lisser une partie de ce pic.

Je vais regarder la solution proposée, sinon j'essaierai de coordonner une automatisation dans HA avec l'heure de passage de réduit à confort du thermostat.
Merci
