### ISSUE TITLE
Entity None 

### ISSUE THREAD

**Issue by kfran78** [TheGui01/Frisquet-connect-for-home-assistant#31]
Bonjour

au re démarrage de mon HAOS, j'ai ce log. pourtant l'intégration fonctionne. 

Enregistreur: homeassistant.components.climate
Source: components/climate/__init__.py:384
intégration: Thermostat (documentation, problèmes)
S'est produit pour la première fois: 12:16:19 (1 occurrences)
Dernier enregistrement: 12:16:19

Entity None (<class 'custom_components.frisquet_connect.climate.FrisquetConnectEntity'>) implements HVACMode(s): heat, auto, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/TheGui01/Friquest-connect-for-home-assistant/issues

Core
2024.12.2
Supervisor
2024.11.4
Operating System
14.0
Interface utilisateur
20241127.7

**Comment by TheGui01** [comment]
Salut @kfran78 
Effectivement, je n'ai pas implémenté la fonction on/off car Frisquet ne nous permet pas d'éteindre/allumer la chaudière

Ce warning peut être ignoré

**Comment by kfran78** [comment]
ok c'est plus clair ! merci.
