### ISSUE TITLE
Pytz function error

### ISSUE THREAD

**Issue by kfran78** [TheGui01/Frisquet-connect-for-home-assistant#32]
Au re démarrage depuis quelque temps j'ai celà étant étonné de voir "Africa/Abidjan'" (étant en France)

Enregistreur: homeassistant.util.loop
Source: util/loop.py:136
S'est produit pour la première fois: 12:16:16 (1 occurrences)
Dernier enregistrement: 12:16:16

Detected blocking call to open with args ('/usr/local/lib/python3.13/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'frisquet_connect' at custom_components/frisquet_connect/climate.py, line 361: desired_timezone = pytz.timezone(self.tz) (offender: /usr/local/lib/python3.13/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/TheGui01/Friquest-connect-for-home-assistant/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2383, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 237, in async_setup_entry return await hass.data[DATA_COMPONENT].async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 197, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/frisquet_connect/climate.py", line 58, in async_setup_entry entity = FrisquetConnectEntity( File "/config/custom_components/frisquet_connect/climate.py", line 157, in __init__ self._attr_preset_mode = self.defPreset( File "/config/custom_components/frisquet_connect/climate.py", line 317, in defPreset return self.getPresetFromProgramation() File "/config/custom_components/frisquet_connect/climate.py", line 361, in getPresetFromProgramation desired_timezone = pytz.timezone(self.tz)

**Comment by TheGui01** [comment]
Salut @kfran78 
C'est la fonction qui permet de déterminer sous quelle fuseau on se trouve pour interpréter correctement la programmation.

Si votre programmation est correctement reflètée : changement de mode Réduit /Confort en dehors d'eventuelle dérogation.
Alors cette erreur n'a oas d'impact.

J'ai néanmoins prévu de changer cette fonction quand je trouverai du temps

**Comment by kfran78** [comment]
ok c'est noté ! merci et encore super boulot pour la communauté des Frisquet :)

**Comment by TheGui01** [comment]
corrigé dans la version [v2.1.10](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/releases/tag/v2.1.10)

**Comment by kfran78** [comment]
Top. Je viens de mettre à jour .
