### ISSUE TITLE
message d'avertissement

### ISSUE THREAD

**Issue by icna99a** [TheGui01/Frisquet-connect-for-home-assistant#5]
Bonjour,
En fouillant les logs pour d'autres raison je suis tombé sur ce message :

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Thermostat (documentation, issues)
First occurred: 17:19:08 (1 occurrences)
Last logged: 17:19:08

Entity None (<class 'custom_components.frisquet_connect.climate.FrisquetConnectEntity'>) implements HVACMode(s): heat, auto, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/TheGui01/Friquest-connect-for-home-assistant/issues

**Comment by TheGui01** [comment]
Bonjour  @icna99a ,
Frisquet n'offre pas la possibilité d'arrêter la chaudière donc les fonctions turn_on/turn_off ne sont pas implémentées.

**Comment by icna99a** [comment]
Merci pour l'info et désolé du faux report du coup !!!
