### ISSUE TITLE
Hors sujet volontaire : pas de connexion au serveur depuis la passerelle

### ISSUE THREAD

**Issue by JC38** [TheGui01/Frisquet-connect-for-home-assistant#6]
Bonjour,
Je profite de cet add-on qui par définition concerne des utilisateurs Frisquet pour savoir si votre chaudière vous remonte également un message de perte de connexion au serveur. Il me semble que cela a commencé vendredi.
Si je reboote la passerelle Frisquet, ses voyants réseaux redeviennent normaux pendant quelques temps puis se remettent encore à clignoter quelques temps après. Je suis connecté en ethernet et je peux pinguer ma gateway. 
J'ai du mal à localiser le problème, interne ou externe. Du coup, je vous sollicite pour savoir si tout est ok chez vous.
Merci de votre aide.

**Comment by ahcenezer** [comment]
Bonjour, RAS de mon coté. 
à disposition si tu as besoins d’autres informations.

**Comment by TheGui01** [comment]
Bonjour @JC38 ,

J'ai un soucis similaire, aussi depuis vendredi : j'ai des ordres qui ne sont pas pris en compte. Du moins je reçois des messages de Frisquet me disant que ma demande de dérogation n'a pas été prise en compte.  
Je pense que le problème est coté serveur. 
Patientons une semaine pour voir si cela persiste.

**Comment by JC38** [comment]
Bonjour,
Je suis rentré hier en fin de journée et les messages ont disparu. Je pense qu'effectivement le problème était côté infra Frisquet.

**Comment by TheGui01** [comment]
> Bonjour,
> Je profite de cet add-on qui par définition concerne des utilisateurs Frisquet pour savoir si votre chaudière vous remonte également un message de perte de connexion au serveur. Il me semble que cela a commencé vendredi.
> Si je reboote la passerelle Frisquet, ses voyants réseaux redeviennent normaux pendant quelques temps puis se remettent encore à clignoter quelques temps après. Je suis connecté en ethernet et je peux pinguer ma gateway. 
> J'ai du mal à localiser le problème, interne ou externe. Du coup, je vous sollicite pour savoir si tout est ok chez vous.
> Merci de votre aide.

Bonjour @JC38 ,

J'ai exactement le même soucis, aussi depuis vendredi.
    Est ce que cela freeze les mise a jour des températures ambiantes ?
De mon côté, ca bloque, parfois les ordres vers les serveurs frisquet, mais tout remonte bien de ma chaudière, vers frisquet connect

**Comment by JC38** [comment]
12h15 : je crois que je n'ai plus vu de message depuis 11h du matin. A suivre... Mais bon, je n'ai pas le nez devant la chaudière pour voir si le message revient puis disparait à nouveau. J'ai regardé s'il y avait un peu de comm. de la part de Frisquet mais ils semblent silencieux (Twitter, site web).

**Comment by JC38** [comment]
Bonjour, 
Pour info, plus de problème depuis hier fin de matinée. Je ferme le ticket.

**Comment by TheGui01** [comment]
Top merci @JC38

**Comment by JC38** [comment]
A midi, j'ai vu que c'était à nouveau en carafe. On se fait blacklister par Frisquet ??

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TheGui01** [comment]
@JC38 
Je me demande....

Mais pour ma part je n'ai plus de soucis

Mon fils vient de rentrer et a désactivé l'alarme ce qui a lancé l'annulation de la dérogation en cours et tout le semble ok.

Peux tu essayer de reboot le boitier ET ta chaudière?
Si ca continue apres, peut etre desinstaller mon integration qq tems pour voir si le problème persiste?

**Comment by Amapem** [comment]
De mon coté je ne vois pas de dysfonctionnement mais dans l'historique des anomalies sur la chaudière j'ai plein de "FRISQUE CONNECT : SERVEUR INACCESSIBLE" environ toutes les heures.

Effectivement je pense que l'intégration perturbe les serveurs Frisquet

**Comment by TheGui01** [comment]
Bonjour,

Les serveurs sont actuellement inaccessible. Nous effectuons une requete toutes les 5 minutes. Ce n'est pas ca qui va faire tomber leur serveur. Nous parlons de 3ko d'échanges de données a chaque fois.
A moins que mon integration est un succès international (j'en doute) Ces requêtes ne vont pas impacter le serveur au point de le faire tomber.
Ils ont probablement des problèmes sur leur infra et/ou des maintenances.

**Comment by JC38** [comment]
Bonjour,
J'ai désactivé l'intégration hier soir, ce matin, j'avais encore le message qui apparaissait. Je pense que le plus simple ce serait de contacter Frisquet et de leur demander s'ils ont un souci ou non :-(. Perso, je n'ai pas de créneau pour le faire avant vendredi. Ils sont pas sur un réseau social pour leur comm ?

**Comment by TheGui01** [comment]
Je viens d'écrire à mon chauffagiste pour savoir si le problème est général.

**Comment by icna99a** [comment]
Chez moi Frisquet Connect est en carafe depuis vendredi.
Je viens d’appeler Frisquet et ils m'ont confirmé que c'est un problème de leur serveur.
J'ai poussé une gueulante, On avait eu une très longue interruption lors de l'incendie du serveur OVH, à l'époque déjà ils n'avaient communiqué que très tard et très peu. Ils n'ont aucune page pour vérifier l'état des serveurs sur leur site et ça me gonfle de devoir tout rebooter et tout vérifier sans savoir d'où vient le problème.
Si on rajoute à ça le protocole fermé et leur box qui ne peut se connecter au Wifi qu'en WPS je ne suis pas prêt de recommander leur solution à des amis !!!!

**Comment by TheGui01** [comment]
Retour de Frisquet a mon chauffagiste :
_Il y a bien un problème de transmission et de lenteur sur le système Frisquet connect qu’ils essayent de résoudre.
Une fois résolu, le système refonctionnera normalement sans que vous ayez une manipulation à faire. (surtout ne rien débrancher)

Les serveurs sont à nouveau dispo cette après midi.
