### ISSUE TITLE
Confort permanent NOK

### ISSUE THREAD

**Issue by Amapem** [TheGui01/Frisquet-connect-for-home-assistant#7]
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/59937802/12311c0f-a6e6-414f-a697-64aea9f87f13)

Hello

chez moi la commande pour le passage en 'Confort permanent" ne fonctionne pas
idem que pour le mode boost

![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/59937802/ed17439c-8b87-48aa-bf1e-eab2d4275715)

**Comment by TheGui01** [comment]
Salut @Amapem ,
Merci pour ton retour ! Je viens de corriger les erreurs (Typo) sur la version v1.7.1
En revanche, pas sur que le boost se comporte bien. De ma compréhension, cela devrait augmenter la Température de consigne du mode confort.
N'hésites pas a me faire un retour si ca ne correspond pas à tes attentes. Je laisse le bug ouvert pour l'instant. Si pas de retour de ta part je clôturerai en fin de semaine.

**Comment by TheGui01** [comment]
@Amapem 
Normalement, pour suprrimer les derog, il faut passer le HVAC mode sur Auto, et non changer le preset mode.

**Comment by Amapem** [comment]
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/59937802/e0b04f17-3fe5-4011-8d42-eae8c5728299)
ici j'ai l'impression que ça n'a aucun effet

**Comment by TheGui01** [comment]
@Amapem 
En fait le HVAC mode restait en auto sur les modes permanent on ne pouvait pas repasser en Auto.
Le fix est pret et fonctionnel. Je pousse une version ce soir au plus tard! Je suis sur le #8 là

**Comment by TheGui01** [comment]
@Amapem Tout bon dans la v1.7.5
