### ISSUE TITLE
Manque icones

### ISSUE THREAD

**Issue by Amapem** [TheGui01/Frisquet-connect-for-home-assistant#8]
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/59937802/fa61e8bd-05b6-4751-824c-ea009fcc52a8)

il manque des icones dans la liste déroulante

Et si on affiche sous forme d'icones ça manque...
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/59937802/bf1d63de-c6a1-4ef6-972b-02ad49e3291a)

C'est pas très important mais on sait jamais ;-)

**Comment by TheGui01** [comment]
@Amapem 
Je n'étais pas passé a coté de ceci mais ce n'était pas possible.
Ca l'est depuis le 4 février dernier !
Je regarde ca et ferai probablement une release cette aprem si je m'en sors.

**Comment by TheGui01** [comment]
@Amapem Ajouté dans le v1.7.5 !
Toute suggestion de nouveau icones est la bienvenue

**Comment by Amapem** [comment]
SUPER !!

![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/59937802/1717a2c7-de15-4dbe-bb71-bdc614c9b4c7)

Merci pour la réactivité
